[WIP] Play a single game
marmelab/15-puzzle-isomorphic pull request #3
Opened 2017-11-24 15:54 UTC by Luwangel

- [x] Create the basic components (buttons, loaders)
- [x] Upgrade the style
- [ ] Connect the core to display a shuffled grid

2017-11-24 16:06 UTC, djhi requested changes

2017-11-24 16:06 UTC, djhi commented on pages/game.js
> +    renderWinnerMessage(isVictory, turn) {
avoid renderXXX methods. Just put the condition directly inside the rendered JSX or extract in another component.

2017-11-24 16:06 UTC, djhi commented on src/components/activityIndicator.js
> +export default class ActivityIndicator extends Component {
If your component just render stuff without any other logic, make it a functional component

2017-11-24 16:06 UTC, djhi commented on src/components/button.js
> +export default class Button extends Component {
same

2017-11-24 16:06 UTC, djhi commented on src/components/grid.js
> +export default class Grid extends Component {
same

2017-11-24 16:06 UTC, djhi commented on src/components/head.js
> +export default function CustomHead() {
```jsx
const CustomHead = () => (JSX);

export default CustomHead;
```

2017-11-24 16:06 UTC, djhi commented on src/components/activityIndicator.js
> +export default class ActivityIndicator extends Component {
Note that this is just a personal preference, not a change request

2017-11-24 16:13 UTC, jdemangeon commented on pages/game.js
> +                    <CustomHead />
There's too much repeated code in this page.

I'll extract all common code (CustomHead, Nav, ...) in a dedicated template (thinks about base.html.twig in Symfony for example).

2017-11-24 16:13 UTC, jdemangeon commented on pages/index.js
> +                <CustomHead />
Same

2017-11-24 16:13 UTC, jdemangeon commented on src/components/button.js
> +export default class Button extends Component {
There's no needs for "Class" Components for simple cases (with no state manipulation) as this button.

You should use Stateless Component in this case (https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc). It's more concise and clearer.

```
const Button = ({ color, icon, label, path }) => (
    <Link href={{ pathname: path }}>
        <a className={`btn ${color ? color : ''}`}>
            <i className="material-icons left">{icon}</i>
            {label}
        </a>
    </Link>
);

Button.propTypes = {...};

export default Button;
```

2017-11-24 16:13 UTC, jdemangeon commented on src/components/button.js
> +export default class Button extends Component {
You're component don't need to re-render each time props changes. If props are the same, there's no reason to re-render. It's called "purity", with "pure" components.

With "class" component, you should extends 
[PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent).

With stateless component, you should "pure" HOC from recompose https://github.com/acdlite/recompose/blob/master/docs/API.md#pure

2017-11-24 16:13 UTC, jdemangeon commented on src/components/button.js
> +            <Link href={{ pathname: path }}>
Same for "purity".

2017-11-24 16:13 UTC, jdemangeon commented on src/components/button.js
> +export default class Button extends Component {
I advice you to read the article below. It'll help you to understand performance considerations in React.

https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html

2017-11-24 16:13 UTC, jdemangeon commented on src/components/grid.js
> +        return (
Same for "purity"

2017-11-24 16:13 UTC, jdemangeon commented on src/components/grid.js
> +                            {row.map(tileValue => {
You can use ternary here.

```
tileValue === 0 ? (<div>...</div>) : (<div>...</div>)
```

2017-11-24 16:13 UTC, jdemangeon commented on src/components/nav.js
> +export default class Nav extends Component {
Same for "purity"

2017-11-27 10:26 UTC, floo51 requested changes

2017-11-27 10:26 UTC, floo51 commented on __tests__/src/components/button.spec.js
> +    it('it should render the Button without error', () => {
it x2

2017-11-27 10:26 UTC, floo51 commented on pages/game.js
> +    renderWinnerMessage(isVictory, turn) {
Having functions like this is usually a sign that the component should be split. That or use an inline if.

2017-11-27 10:26 UTC, floo51 commented on pages/game.js
> +        return (
Too many duplicated code, you can merge both returns into one and use JSX:

```jsx
return (
    <div>
          {shouldShowThisParticularThing &&
               <h1> Hello ! </h1>
          }
    </div>
);
```

2017-11-27 10:43 UTC, djhi requested changes

2017-11-27 10:43 UTC, djhi commented on __tests__/pages/index.spec.js
> +    it('should render Index without error', () => {
`test`, not `it` if you're using jest

2017-11-27 10:43 UTC, djhi commented on __tests__/src/components/activityIndicator.js
> +    it('should render ActivityIndicator without error', () => {
`test`, not `it` if you're using jest

2017-11-27 10:43 UTC, djhi commented on __tests__/src/components/button.spec.js
> +    it('should render the Button without error', () => {
`test`, not `it` if you're using jest

2017-11-27 10:58 UTC, floo51 approved these changes

2017-11-27 11:01 UTC, djhi approved these changes

2017-11-27 11:01 UTC, merged