[WIP] Play offline
marmelab/15-puzzle-isomorphic pull request #6
Opened 2017-11-27 14:15 UTC by Luwangel

- [x] Put the game in cache to allow the user to play offline

2017-11-27 14:18 UTC, Kmaschta commented on src/components/page.js
> +Page.componentDidMount = () => {
Can you transform your Page function into a class in order to put the `componentDidMount` as a class attribut.. ?

2017-11-27 15:06 UTC, floo51 requested changes

2017-11-27 15:06 UTC, floo51 commented on Makefile
> +run-cache: build ## Run the 15-puzzle isomorphic app with cache
Instead of having multiple entry points, it make it easier to document and to maintain to have only one (and use env vars for "feature" flagging)

2017-11-27 15:45 UTC, Kmaschta commented on server.js
> +const port = process.argv.find(val => val === 'port') || 3000;
Nice way to configure the port, but I immediately frown at this line.

Obviously, this is not mandatory, but this line is a potential security issue and you'd better check or cast the type of this output.

<details>
 <summary>Explanation</summary>
 NextJS use the node "http" module. (<a href="https://nodejs.org/api/net.html">doc</a>)

 Its function <a href="https://nodejs.org/api/net.html#net_server_listen">`server.listen`</a> have multiple signatures:
 
```
server.listen(handle[, backlog][, callback])
server.listen(options[, callback])
server.listen(path[, backlog][, callback]) for IPC servers
server.listen([port][, host][, backlog][, callback]) for TCP servers
```
You think that you're using the last one, but it can be any of them.

The third, which takes a path as first argument, can make a potential connection to any filesystem or server.
Just like allowing a user to write in the `src` attribute of an `img` of your web page is an XSS vulnerability, allow a user to make a connection from your app is a security flawn.

It's a common mistake, and an easy solution is to cast the value into a integer and/or check that this value is between the minimum and maximum allowed port.
</details>

2017-11-28 09:27 UTC, floo51 approved these changes

2017-11-28 09:27 UTC, merged